apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: hello
  labels:
    app.kubernetes.io/name: hello
    app.kubernetes.io/component: backend
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app.kubernetes.io/name: hello
    app.kubernetes.io/component: backend
